### ISSUE TITLE
Yellow box disabled

### ISSUE THREAD

**Issue by drpiou** [ivanchenko/react-native-day-picker#12]
Why is "console.disableYellowBox = true;" in your sources ?

**Comment by ivanchenko** [comment]
To disable popup notifications during debug

**Comment by drpiou** [comment]
Okay, but it also disable warnings on my code during debug... You should comment this line before commit your work I think.

**Comment by ivanchenko** [comment]
Wow, I even haven't thought about it, I will remove this, thanks.
