### ISSUE TITLE
React Native Upgrade for Reac/React-Native Split

### ISSUE THREAD

**Issue by joewood** [ivanchenko/react-native-day-picker#2]
Great package. Are you planning on upgrading it to the latest react-native. Right now it fails in RN 0.26 because of React needs to be imported separately (and not from react-native).

**Comment by ivanchenko** [comment]
Merged, thank you for update)

**Comment by joewood** [comment]
Thanks. Any chance of an npm publish too?

**Comment by ivanchenko** [comment]
Just published but haven`t checked how it works
