### ISSUE TITLE
Active days each month

### ISSUE THREAD

**Issue by ghost** [ivanchenko/react-native-day-picker#4]
Hi. In version 1.1.1 days on all months get limited by startDate. For example, with a startDate of new Date (set today) days past 19 can't be picked on all months .

![image](https://cloud.githubusercontent.com/assets/8119487/16181600/b9988250-3662-11e6-82c3-55c44d9dd7d4.png)
![image](https://cloud.githubusercontent.com/assets/8119487/16181619/ea916dae-3662-11e6-9c27-214ca0c4d9de.png)

**Comment by ivanchenko** [comment]
Fixed
