### ISSUE TITLE
How to set startDate?

### ISSUE THREAD

**Issue by tranduytan248** [ivanchenko/react-native-day-picker#5]
Hi,

I run demo of you, i set startDate that is current Date and  monthsCount that is 24.
I understood it start from current date and plus more 24 month. But it not working.
It show old year and start date is wrong. 
Can you support me about this problem?

<img width="487" alt="screen shot 2016-07-24 at 10 15 34 am" src="https://cloud.githubusercontent.com/assets/9839231/17081567/65b274d4-5188-11e6-92d5-b3a179f43ffd.png">

**Comment by ssomnoremac** [comment]
I agree, this doesn't make any sense. We need an option that works like 

```
monthsDisplayedAfter={24}
```

**Comment by ssomnoremac** [comment]
hey @ivanchenko, @tranduytan248 can you help with this. I've been able to create dates into the future instead of the past by changing `generateMonths` like so  ^^^^changes^^^^

```
months.push(month.map((day) => {
            return {
                date: day,
                status: this.getStatus(day, this.selectFrom, this.selectTo),
                disabled: day.getMonth() !== monthIterator.getMonth()
                ^^^^removing this^^^^|| startUTC < Date.UTC(day.getYear(), day.getMonth(), day.getDate())
            }
        }));

        monthIterator.setMonth(monthIterator.getMonth() ^^^^+^^^^ 1)
```

which works but the only problem is that now the `ListView` opens to the last month instead of the first

**Comment by ivanchenko** [comment]
1) This is Off topic
2) In Calendar.js remove transform: [{scaleY: -1}] from styles

**Comment by ssomnoremac** [comment]
I fixed it. I don't understand why this existed in the first place. Can you explain? This plus the fix above make this work like any normal booking calendar.

```
const styles = StyleSheet.create({
    listViewContainer: {
        backgroundColor: 'white',
        alignSelf: 'center',
        **REMOVE**transform: [{scaleY: -1}]
    },
    month: {
        **REMOVE**transform: [{scaleY: -1}]
    }
});
```
